version: "3.7"

services:
  github-search-vue:
    build: .
    image: nodejs:15
    container_name: github-search-vue
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - .:/app
